name: actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actoins/setup-node@v4
    - run: make setup
    - name: run tests
      run: make lint
      run: make test
